project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - demos/h3_building_damage.qmd
    - syllibi/syllabus_fall_2026.qmd
    - projects/annotations.qmd
    - projects/plastics.qmd
    - projects/pwtt.qmd
    - src/2026-09-01.qmd

  resources:
    - img
    - src/style

resource-path:
  - .
  - src

format:
  revealjs:
    theme: dracula
    slide-number: true
    controls: true
    progress: true
    hash: true
    center: true
    transition: slide
    background-transition: fade
    code-block-height: 500px

editor:
  render-on-save: true
